apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fjic2ardd-nodejs
  janus-idp.io/tekton: fjic2ardd-nodejs
  backstage.io/kubernetes-id: fjic2ardd-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fjic2ardd-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
