apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fjic2ardd-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fjic2ardd-nodejs 
  name: fjic2ardd-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: fjic2ardd-nodejs 
